definitions:
  models.CreateArticleRequest:
    description: Тело запроса для создания пользователя
    properties:
      content:
        type: string
      title:
        type: string
    required:
    - content
    - title
    type: object
  models.CreateUserRequest:
    description: Тело запроса для создания пользователя
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  models.LoginRequest:
    description: Тело запроса для аутентификации пользователя
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.SignUpUserRequest:
    description: Тело запроса для регистрации пользователя
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  models.UpdateUserBody:
    description: Тело запроса для обновления пользователя
    properties:
      email:
        type: string
      firstName:
        type: string
    type: object
  models.UserResponse:
    description: Тело ответа после cоздания пользователя
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    required:
    - createdAt
    - email
    - name
    - updatedAt
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Сервис с новостными статьями и блогами.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Good News on Go
  version: "1.0"
paths:
  /api/v1/current_user:
    get:
      description: Get token from users cookee
      operationId: get-current-user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.UserResponse'
            type: array
      summary: get current user
      tags:
      - Authentication
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Authenticate User in app with given request body
      parameters:
      - description: Введите данные для авторизации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: user authentication
      tags:
      - Authentication
  /api/v1/logout:
    get:
      description: Clear JWT token by setting an empty value and expired time in the
        cookie
      operationId: logout-current-user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: logout current user
      tags:
      - Authentication
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: Register User in app with given request body
      parameters:
      - description: Введите данные для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignUpUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: user registration
      tags:
      - Authentication
  /articles:
    post:
      consumes:
      - application/json
      description: Creating Article in DB with given request body
      parameters:
      - description: Введите данные статьи
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateArticleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: create new article
      tags:
      - Articles
  /users:
    get:
      description: Get all users from db
      operationId: get-all-users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.UserResponse'
            type: array
      summary: get all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Creating User in DB with given request body
      parameters:
      - description: Введите данные пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: create new user
      tags:
      - Users
  /users/{id}:
    delete:
      description: Delete a user item by ID
      operationId: delete-user-by-id
      parameters:
      - description: userUUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "404":
          description: Not Found
          schema:
            items:
              type: string
            type: array
      summary: delete a user item by ID
      tags:
      - Users
    get:
      description: Get a user by ID
      operationId: get-user-by-id
      parameters:
      - description: userUUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "404":
          description: Not Found
          schema:
            items:
              type: string
            type: array
      summary: get a user by ID
      tags:
      - Users
    put:
      description: Update user by ID
      operationId: delete-user-by-id
      parameters:
      - description: userUUID
        in: path
        name: id
        required: true
        type: string
      - description: Введите данные пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "404":
          description: Not Found
          schema:
            items:
              type: string
            type: array
      summary: update user by ID
      tags:
      - Users
swagger: "2.0"
