definitions:
  main.article:
    properties:
      id:
        type: string
      task:
        type: string
    type: object
  main.message:
    properties:
      message:
        type: string
    type: object
host: 127.0.0.1:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Сервис с новостными статьями и блогами.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Good News on Go
  version: "1.0"
paths:
  /article:
    get:
      description: Get all items in the article list
      operationId: get-all-articles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.article'
      summary: get all items
      tags:
      - Articles
    post:
      description: Add a new item to the article list
      operationId: create-article
      parameters:
      - description: article data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.article'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.article'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.message'
      summary: add a new item
      tags:
      - Articles
  /article/{id}:
    delete:
      description: Delete a article item by ID
      operationId: delete-article-by-id
      parameters:
      - description: article ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.article'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.message'
      summary: delete a article item by ID
      tags:
      - Articles
    get:
      description: Get a article item by ID
      operationId: get-article-by-id
      parameters:
      - description: article ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.article'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.message'
      summary: get a article item by ID
      tags:
      - Articles
  /nice:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
swagger: "2.0"
